name: GitHub Action - Deploy and Update ENVs on Coolify
author: devevandro
description: Deploy and Update ENVs on Coolify

inputs:
  coolify_url:
    description: 'Coolify URL'
    required: true
  coolify_token:
    description: 'Coolify Access Token'
    required: true
  coolify_app_uuid:
    description: 'Coolify App UUID'
    required: true
  secrets:
    description: 'Github secrets to be updated on Coolify'
    required: false
  secrets_to_exclude:
    description: 'Github secrets to be excluded from the update on Coolify'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
