name: Coolify Deploy

on:
  push:
    branches: [fix/hour]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          coolify_url: ${{ secrets.COOLIFY_URL }}
          coolify_token: ${{ secrets.COOLIFY_TOKEN }}
          coolify_app_uuid: ${{ secrets.COOLIFY_APP_UUID }}
          secrets: ${{ toJson(secrets) }}
