name: "Hello"

on:
  push:
    branches: [stage]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          coolifyUrl: ${{ secrets.COOLIFY_URL }}
          coolifyToken: ${{ secrets.COOLIFY_TOKEN }}
          coolifyAppUuid: ${{ secrets.COOLIFY_APP_UUID }}
          secrets: ${{ toJson(secrets) }}
